---
docker: &docker
  docker#v3.0.1:
    user: buildkite
    always-pull: true
    image: library.pdx.aws.av.lyft.net/ci/ci-cpp-bionic:1.1.3778
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/buildkite-agent/.ssh/:/home/buildkite/.ssh/
    environment:
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_PIPELINE_SLUG
      - BUILDKITE_ORGANIZATION_SLUG
      - BUILDKITE_VAULTBUILDKITEPLUGIN_INFRA_NEXUS_BUILDKITE_USERNAME
      - BUILDKITE_VAULTBUILDKITEPLUGIN_INFRA_NEXUS_BUILDKITE_PASSWORD
      - BUILDKITE_VAULTBUILDKITEPLUGIN_INFRA_GITHUB_LYFT_AUTONOMOUS_CI_PASSWORD

vault: &vault
  ssh://github.com-vbkp/lyft/vaultbuildkiteplugin#v0.1.0:
    domain: vault.pdx.l5.woven-planet.tech
    secrets:
      - infra/nexus/buildkite=username
      - infra/nexus/buildkite=password
      - infra/github/lyft-autonomous-ci=password

retries: &retries
  automatic:
    - exit_status: 128
      limit: 3

steps:
  - label: ":hammer: Lint"
    timeout: 5
    agents:
      queue: cpu-small
    command: .buildkite/install_linters.sh && ./lint.sh ./
    retry:
      <<: *retries
    plugins:
      <<: *vault
      <<: *docker

  - label: ":hammer: Unit Tests"
    timeout: 5
    agents:
      queue: cpu-small
    command: .buildkite/setup_env.sh && bazel test --test_output=errors //... && bazel build //...
    retry:
      <<: *retries
    plugins:
      <<: *vault
      <<: *docker

  - wait

  - label: ":ship: Release"
    timeout: 5
    agents:
      queue: cpu-small
    branches: main
    commands:
      - "sudo apt update"
      - "sudo apt install zip -y"
      - "./zip_and_upload_to_artifactory.sh $(cat VERSION).${BUILDKITE_BUILD_NUMBER}"
    retry:
      <<: *retries
    plugins:
      <<: *vault
      <<: *docker

  - wait

  - label: ":rocket: System Test: Import slog_cc"
    timeout: 5
    agents:
      queue: cpu-small
    branches: main
    commands:
      - ".buildkite/setup_env.sh"
      - "cd test_import/example_project_cc/"
      - "./prepare_workspace.sh $(cat ../../VERSION).${BUILDKITE_BUILD_NUMBER}"
      - "bazel test --test_output=errors src:slog_cc_test"
    retry:
      <<: *retries
    plugins:
      <<: *vault
      <<: *docker

  - label: ":rocket: System Test: Import slog_py"
    timeout: 5
    agents:
      queue: cpu-small
    branches: main
    commands:
      - ".buildkite/setup_env.sh"
      - "cd test_import/example_project_py/"
      - "./prepare_workspace.sh $(cat ../../VERSION).${BUILDKITE_BUILD_NUMBER}"
      - "bazel test --test_output=errors src:slog_py_test"
    retry:
      <<: *retries
    plugins:
      <<: *vault
      <<: *docker
